### PR TITLE
Standalone build and build action

### PR DESCRIPTION
**Pull request by Daft-Freak**
First few patches from my fork that definitely don't break anything. (Unlike the rest :laughing:)

Probably needs a README update :thinking:

### CODE REVIEW

**Comment by bernhardstrobl** [comment]
I remember the template provided by the sdk not working correctly (not finding the sdk or something). Will check that it builds and update the ReadMe in the coming days. Thanks!

**Comment by bernhardstrobl** [comment]
So I had to add the paths into the cmake file of the project directly since it was not finding the paths of the SDKs.
I use the command line for building so that just might be expected behaviour. 
Works if these lines are added so just going to roll with it for the time being:

set(PICO_SDK_PATH /Users/bernhard/pico/pico-sdk)
set(PICOSYSTEM_DIR /Users/bernhard/picosystem/picosystem)

**Comment by Daft-Freak** [comment]
Usually you would do something like `cmake -DPICO_SDK_PATH=/path/to/pico-sdk -DPICOSYSTEM_DIR=/path/to/
/picosystem [rest of command]` then forget about it until you need to recreate the build dir.

(This reminds me I was going to pull out all the stuff before switching the SDK (which I think is https://github.com/bernhardstrobl/Pico3D/compare/main...Daft-Freak:Pico3D:a0fe36a469ed82a5760f0129d334ae07fb92033c), but uh, distractions :laughing: )

**Comment by bernhardstrobl** [comment]
Works like a charm! Will modify the Readme to reflect that ^^.
No rush with the changes, still prepping ideas for the next big engine example which probably won't make too many changes to the engine itself (famous last words). Have to deal with plenty of distractions to get started as well however 🤣

**Comment by bernhardstrobl** [comment]
When you have time, can you send in a pull request for the changes? GitHub won't let me integrate directly and I think I might need to fix a few tiny bits in the engine for my next example. Thanks ☺️!

**Pull request merged**
